//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: player_list.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef LRS_PLAYER_LIST_BASE_CLASSES_H
#define LRS_PLAYER_LIST_BASE_CLASSES_H

#define wxDEBUG_LEVEL 0
#include <wx/artprov.h>
#include <wx/panel.h>
#include <wx/ribbon/art.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/buttonbar.h>
#include <wx/ribbon/page.h>
#include <wx/ribbon/panel.h>
#include <wx/settings.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/xrc/xmlres.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

#include <functional>
#include <map>
#include <string>
#include <vector>

class personpanel : public wxRibbonPanel
{
    wxRibbonButtonBar* bar;

  public:
    wxTextCtrl* tc;
    int         m_index;
    bool        is_dead;
    personpanel(wxWindow* paren, int index);
    void add(std::string name, std::function< void() > func = []() {});
    std::map< std::string, int > buttonmap;
    void remove(std::string);
	void set_role(std::string role_name);
	void clear_role();
};
class pl_panel
{
    wxRibbonArtProvider* defaulp;
    wxRibbonArtProvider* redpro;

  protected:
    wxRibbonPage* left_page;
    wxRibbonPage* right_page;

  public:
    std::vector< personpanel* > pannels;
    void set_status(size_t index, bool is_dead);
    pl_panel(wxRibbonPage* left_page, wxRibbonPage* right_page, size_t size);
    virtual ~pl_panel();
};

#endif
